# This file generates the GitHub Actions matrix.

board:
  - nice_nano_v2

shield:
  - charybdis_left
  - charybdis_right

format:
  - bt

keymap:
  - qwerty

include:
  - board: nice_nano_v2
    shield: charybdis_right
    keymap: qwerty
    snippet: studio-rpc-usb-uart
